#include "../headers/Aluno.h"
#include "../headers/Departamento.h"
#include "../headers/Disciplina.h"
#include "../headers/Pessoa.h"
#include "../headers/Professor.h"
#include "../headers/Universidade.h"